config/routes.rb
Rails.application.routes.draw do

  # Table endpoints
  get '(:shortcode)', to: 'table#index', as: 'table_view'

  # API endpoints
  scope :api do
    constraints format: :json do
      scope :v1 do
        get 'list', to: 'titles#index'
      end
    end
  end


  root to: 'table#index'

end

app/controllers/table_controller.rb
class TableController < ApplicationController
  def index

    @institutions = Institution.all
    @institution = Institution.find_by_shortcode(params[:shortcode])

    sql = "SELECT DISTINCT(material_type) FROM titles" + (@institution && @institution.shortcode != 'usg' ? " where institution_id=#{@institution.id}" : "") +
     " ORDER BY material_type"
    records = ActiveRecord::Base.connection.exec_query(sql)
    @media_types = records.rows
    @media_types.unshift ['--','']

    @libraries = []
    if @institution and @institution.shortcode != 'usg'
      sql = "SELECT DISTINCT(library) FROM titles where institution_id=#{@institution.id} and library != '' ORDER BY library"
      records = ActiveRecord::Base.connection.exec_query(sql)
      @libraries = records.rows
      @libraries.unshift ['--','']
    end

    respond_to do |format|
      format.html
      format.json { render json: TitlesDatatable.new(view_context, @institution) }
    end
  end
end

app/views/table/_institution_picker.html.erb
<div class="row">
  <div class="col">
    <form action="#">
      <div class="form-group">
        <label for="institution">Change Institution: </label>
        <select name="institution" id="institution-picker" class="form-control">
          <% selected_institution = @institution ? @institution.shortcode : 'usg' %>
          <%= options_for_select(
                  @institutions.order(:name).collect { |i| [i.name, i.shortcode] }, selected_institution
              ) %>
        </select>
      </div>
    </form>
  </div>
</div>

app/views/table/_library_picker.html.erb
  <div class="col-3">
    <form action="#">
      <div class="form-group">
        <label for="library">Filter by Library: </label>
        <select name="library" id="library-picker" class="form-control">
          <% selected_library = @library ? @library : '' %>
          <%= options_for_select(@libraries, selected_library) %>
        </select>
      </div>
    </form>
  </div>

app/views/table/_media_type_picker.html.erb
  <div class="col-3">
    <form action="#">
      <div class="form-group">
        <label for="media_type">Filter by Media Type: </label>
        <select name="media_type" id="media_type-picker" class="form-control">
          <% selected_media_type = @media_type ? @media_type : '' %>
          <%= options_for_select(@media_types, selected_media_type) %>
        </select>
      </div>
    </form>
  </div>

app/views/table/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/colreorder/1.5.1/js/dataTables.colReorder.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>GIL New Titles</title>
  <style>
    div.dt-buttons {
      float: left;
    }

    div.titles_filter {
      float: right;
    }
    table td {
      word-wrap: break-word;
      white-space: pre-wrap;
    }
    .thumbnail img {
      max-height: 100px;
    }
  </style>
</head>
<div class="container">
  <div class="row align-items-center">
    <div class="col">
      <h1>New Titles <%= "for #{ @institution.name }" if @institution && !@institution.usg? %></h1>
    </div>
    <% if @institution && !@institution.usg? %>
      <div class="col-3">
        <%= image_tag @institution.image, class: 'img-fluid float-right' %>
      </div>
    <% end %>
  </div>
  <%= render 'institution_picker' %>
  <div class="row">
    <%= render 'media_type_picker' %>
    <div class="col-3">
      <label for="media_type">Filter by Received Date: </label>
        <select name="receiving_date" id="date-picker" class="form-control">
          <option value="">--</option>
          <option value="7">Last week</option>
          <option value="14">Last two weeks</option>
          <option value="31">Last month</option>
        </select>
    </div>
    <div class="col-3">
      <label for="record-type">Filter by Record Type: </label>
        <select name="record-type" id="record-type-picker" class="form-control">
          <option value="">All</option>
          <option>Physical</option>
          <option>Electronic</option>
        </select>
    </div>
    <div class="col-3">
      <label for="lc-class">Filter by LC Classification: </label>
      <select name="lc-class" id="lc-class-picker" class="form-control">
        <option value="">--</option>
        <option value="A">A - GENERAL WORKS</option>
        <option value="B">B - PHILOSOPHY. PSYCHOLOGY. RELIGION</option>
        <option value="C">C - AUXILIARY SCIENCES OF HISTORY</option>
        <option value="D">D - WORLD HISTORY</option>
        <option value="E">E - HISTORY OF THE AMERICAS</option>
        <option value="F">F - HISTORY OF THE AMERICAS</option>
        <option value="G">G - GEOGRAPHY. ANTHROPOLOGY. RECREATION</option>
        <option value="H">H - SOCIAL SCIENCES</option>
        <option value="J">J - POLITICAL SCIENCE</option>
        <option value="K">K - LAW</option>
        <option value="L">L - EDUCATION</option>
        <option value="M">M - MUSIC AND BOOKS ON MUSIC</option>
        <option value="N">N - FINE ARTS</option>
        <option value="P">P - LANGUAGE AND LITERATURE</option>
        <option value="Q">Q - SCIENCE</option>
        <option value="R">R - MEDICINE</option>
        <option value="S">S - AGRICULTURE</option>
        <option value="T">T - TECHNOLOGY</option>
        <option value="U">U - MILITARY SCIENCE</option>
        <option value="V">V - NAVAL SCIENCE</option>
        <option value="Z">Z - INFORMATION RESOURCES (GENERAL)</option>
      </select>
    </div>
  </div>
  <div class="row">
    <% unless @libraries.length < 3 %>
      <%= render 'library_picker' %>
    <% end %>
  </div>
  <div class="row">
    <div class="col">
      <table id="titles" class="table table-bordered table-hover" data-source="<%= table_view_url(institution: @institution, format: "json") %>">
        <thead class="thead-light">
        <tr>
          <th>Received</th>
          <th></th>
          <th>Title</th>
          <th>Author</th>
          <th>Media Type</th>
          <th>Publisher</th>
          <th>Call No.</th>
          <th>Norm. Call No.</th>
          <th>Library</th>
          <% if @institution && !@institution.usg? %><th>Location</th><% end%>
          <% unless @institution && !@institution.usg? %><th>Institution</th><% end %>
        </tr>
        </thead>
        <tbody></tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    var $table = $('#titles');
    //$table.on('order.dt', loadThumbnails);
    //$table.on('search.dt', loadThumbnails);
    //$table.on('page.dt', loadThumbnails);
    var datatable = $table.DataTable({
        sPaginationType: "full_numbers",
        bProcessing: true,
        bServerSide: true,
        columns: [
            { orderData: 0, targets: 0 },
            { orderData: 1, targets: 1 },
            { orderData: 2, targets: 2 },
            { orderData: 3, targets: 3 },
            { orderData: 4, targets: 4 },
            { orderData: 5, targets: 5 },
            { orderData: [6,7], targets: 6 },
            { targets: 7, visible: false },
            { orderData: 8, targets: 8 },
            { orderData: 9, targets: 9 }
          ],
        dom: 'lBfrtip',
        colReorder: true,
        sAjaxSource: $table.data('source'),
        lengthMenu: [25, 50, 100, 200],
        fnServerParams: function ( aoData ) {
          aoData.push( { "name": "media_type", "value": $('#media_type-picker').val() } );
          aoData.push( { "name": "receiving_date", "value": $('#date-picker').val() } );
          aoData.push( { "name": "library", "value": $('#library-picker').val() } );
          aoData.push( { "name": "lc_class", "value": $('#lc-class-picker').val() } );
          aoData.push( { "name": "record_type", "value": $('#record-type-picker').val() } );
        },
        buttons: [
            'copy', 'csv'
        ]
    });

    $("#institution-picker").change(function(){
        window.location.href = '<%= table_view_url %>' + this.value;
    });

    $("#media_type-picker").change(function(){
      datatable.draw();
    });

    $("#date-picker").change(function(){
      datatable.draw();
    });

    $("#library-picker").change(function(){
      datatable.draw();
    });

    $("#lc-class-picker").change(function(){
      datatable.draw();
    });

    $("#record-type-picker").change(function(){
        datatable.draw();
    });
  });
/*

  This is working Google Books API code, but I kept hitting quota limits.
  If quota limits are raised or purchased, uncomment this code and the
  code in the datatable.


  const loadThumbnails = function(){
    console.log('got here');
    $('.thumbnail').each(function(i,thumb){
      fetchThumbnail(thumb);
    });
  };

  const fetchThumbnail = function(thumb){
    const isbns = fetchIsbns(thumb);
    isbns.forEach(function(isbn){
      $.ajax({
        dataType: 'json',
        url: 'https://www.googleapis.com/books/v1/volumes?q=isbn:' + isbn + "&key=AIzaSyC9qxrmXhe6u2Z7MDkW6354R1-mh7RvCMA",
        success: handleResponse
      });
    });
  };


  const handleResponse = function( response ) {
    $.each( response.items, function( i, item ) {
      const thumb = item.volumeInfo.imageLinks.smallThumbnail;
      const isbn = parsePreviewLinkForIsbn(item.volumeInfo.previewLink);
      const img = $('div[data-isbn*='+ isbn + '] img')
      if ( img.attr('src') == '' ) {
        img.attr('src', thumb)
      }
    });
  }

  const parsePreviewLinkForIsbn = function(previewLink) {
    const regex = /isbn:(.*)&hl/;
    const match = previewLink.match(regex);
    return match[1];
  }

  const fetchIsbns = function(thumb){
    return $(thumb).data('isbn').split('; ');
  }; */
</script>